### Read more at config document: https://github.com/Limine-Bootloader/Limine/blob/v12.x/CONFIG.md

### Theme
interface_resolution: 1920x1080
interface_branding: Limine
interface_branding_colour: 8fbcbb
interface_help_colour: a3be8c

term_palette: 3b4252;bf616a;a3be8c;ebcb8b;5e81ac;b48ead;88c0d0;d8dee9
term_palette_bright: 4c566a;bf616a;a3be8c;ebcb8b;81a1c1;b48ead;8fbcbb;eceff4
term_background: ff2e3440
term_foreground: e5e9f0
term_background_bright: 434c5e
term_foreground_bright: eceff4

### Show warning instead of panic on hash mismatch
hash_mismatch_panic: no

### Hide Limine
#quiet: yes
timeout: 6

### Boot the default entry
#default_entry: 2
default_entry: Artix Linux/linux-cachyos
remember_last_entry: no
