#################
#### MANGOWM ####
#################

# https://mangowm.github.io/docs

source = ./mango/autostart.conf
source = ./mango/env.conf
source = ./mango/binds.conf
source = ./mango/appearance.conf
source = ./mango/layout.conf
source = ./mango/input.conf
source = ./mango/animations.conf
source = ./mango/layout.conf
source = ./mango/monitors.conf
source = ./mango/rules.conf
