####################
#### ANIMATIONS ####
####################

# https://mangowm.github.io/docs/visuals/animations

animations = 1
layer_animations = 1
animation_fade_in = 1
animation_fade_out = 1

animation_type_open = zoom
animation_type_close = zoom

tag_animation_direction = 1

zoom_initial_ratio = 0.3
zoom_end_ratio = 0.8
fadein_begin_opacity = 0.5
fadeout_begin_opacity = 0.8

# Timing
animation_duration_move = 479
animation_duration_open = 410
animation_duration_close = 149
animation_duration_tag = 194
animation_duration_focus = 539

# Curves
animation_curve_move = 0.22,1,0.36,1
animation_curve_open = 0.22,1,0.36,1
animation_curve_close = 0,0,1,1
animation_curve_tag = 0.22,1,0.36,1
animation_curve_focus = 0.22,1,0.36,1
animation_curve_opafadeout = 0,0,0.58,1
animation_curve_opafadein = 0,0,0.58,1