####################
#### APPEARANCE ####
####################

# https://mangowm.github.io/docs/visuals/

# Colours
rootcolor = 0x2e3440ff
bordercolor = 0x707d99bb
dropcolor = 0x8fbcbb00
splitcolor = 0x5e81acff
focuscolor = 0x8fbcbbff
urgentcolor = 0xbf616aff
shadowscolor = 0x2e3440ff
maximizescreencolor = 0x88c0d0ff
scratchpadcolor = 0x5e81acff
globalcolor = 0x2e6b69ff
overlaycolor = 0x226e83ff

group_bar_decorate_fg_color = 0xeceff4ff
group_bar_decorate_bg_color = 0x444c5eff
group_bar_decorate_focus_fg_color = 0x2e3440ff
group_bar_decorate_focus_bg_color = 0x8fbcbbff
group_bar_decorate_border_color = 0x707d99ff

jump_label_decorate_fg_color = 0xeceff4ff
jump_label_decorate_bg_color = 0x444c5eff
jump_label_decorate_focus_fg_color = 0x2e3440ff
jump_label_decorate_focus_bg_color = 0x8fbcbbff
jump_label_decorate_border_color = 0x707d99ff

# Window effects
blur = 1
blur_layer = 1
blur_optimized = 0
blur_params_radius = 3
blur_params_num_passes = 4
blur_params_noise = 0.02
blur_params_brightness = 0.9
blur_params_contrast = 0.9
blur_params_saturation = 1.2

border_radius = 10

focused_opacity = 1.0
unfocused_opacity = 0.60

shadows = 1
layer_shadows = 0
shadow_only_floating = 1
shadows_size = 4
shadows_blur = 15
shadows_position_x = 0
shadows_position_y = 0

# Gaps & borders
smartgaps = 1
gappih = 5
gappiv = 5
gappoh = 10
gappov = 10

borderpx = 2
no_radius_when_single = 1

# Group bar
group_bar_decorate_font_desc = Noto Sans 10

group_bar_decorate_border_width = 2
group_bar_decorate_corner_radius = 10

# Jump labels
jump_label_decorate_font_desc = Noto Sans 10

jump_label_decorate_border_width = 2
jump_label_decorate_corner_radius = 10

# Cursor
cursor_theme = Adwaita
cursor_size = 24