###################
#### AUTOSTART ####
###################

# https://mangowm.github.io/docs/configuration/basics#autostart

exec-once = swaybg -i ~/.wallpapers/nord.jpg
exec-once = waybar
exec-once = wl-clip-persist --clipboard regular
exec-once = swaync
exec-once = swayosd-server
exec-once = swayidle
exec-once = /lib/hyprpolkitagent/hyprpolkitagent
exec-once = wl-paste --watch clipvault store
exec-once = steam -silent
