###################
#### AUTOSTART ####
###################

# https://mangowm.github.io/docs/configuration/basics#autostart

exec-once = swaybg -i ~/.wallpapers/nord.jpg
exec-once = waybar
exec-once = wl-clip-persist --clipboard regular --reconnect-tries 0
exec-once = swaync
exec-once = swayosd-server && pkexec swayosd-libinput-backend
exec-once = swayidle
exec-once = lxpolkit
exec-once = wl-paste --watch cliphist store
exec-once = nm-applet
exec-once = steam -silent
