###################
#### BEHAVIOUR ####
###################

# https://mangowm.github.io/docs/configuration/miscellaneous
# https://mangowm.github.io/docs/window-management/scratchpad

# Focus
focus_on_activate = 1
sloppyfocus = 1
warpcursor = 1

focus_cross_monitor = 0
focus_cross_tag = 0

# Drag
drag_corner = 4
drag_warp_cursor = 0

drag_tile_to_tile = 1
drag_tile_small = 1

enable_floating_snap = 1
snap_distance = 10

# Scratchpad
scratchpad_cross_monitor = 1
single_scratchpad = 0

scratchpad_width_ratio = 1
scratchpad_height_ratio = 1

# Tags
tag_carousel = 1
# tag_num = 9

# Misc
allow_lock_transparent = 1

idleinhibit_ignore_visible = 0

syncobj_enable=1

xwayland_persistence = 0
