##################
#### MONITORS ####
##################

# https://mangowm.github.io/docs/configuration/monitors

monitorrule = name:DP-1,width:1920,height:1080,refresh:180.00,x:0,y:0,scale:1

monitorrule = name:eDP-1,width:1366,height:768,refresh:60.02,x:0,y:0,scale:1

allow_tearing = 0 # Enable with Super + T
# hdr_depth = 0
